CREATE DATABASE `pesto-warehouse`;
CREATE TABLE `cities`(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` CHAR(20) NOT NULL,
	`state` CHAR(20),
	PRIMARY KEY(`id`)
);CREATE TABLE `WAREHOUSES`(
	`id` INT NOT NULL AUTO_INCREMENT,
	`WNAME` CHAR(20) NOT NULL,
	`LOCATION` CHAR(20),
	PRIMARY KEY(`id`),
	FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE CASCADE
);CREATE TABLE `CUSTOMER`(
	`CNO` INT NOT NULL AUTO_INCREMENT,
	`CNAME` CHAR(20) NOT NULL,
	`ADDR` VARCHAR(20),
	`CU_CITY` VARCHAR(20),
	PRIMARY KEY(`CNO`)
);CREATE TABLE `STORES`(
	`sid` INT NOT NULL AUTO_INCREMENT,
	`STORE_NAME` CHAR(20) NOT NULL,
	`LOCATION_CITY` CHAR(20),
	PRIMARY KEY(`sid`),
	FOREIGN KEY (warehouse_id) REFERENCES WAREHOUSES(id) ON DELETE CASCADE
);CREATE TABLE `ORDERS`(
	`ONO` INT NOT NULL AUTO_INCREMENT,
	`ODATE` DATE NOT NULL,
	PRIMARY KEY(`ONO`),
	FOREIGN KEY (customer_id) REFERENCES CUSTOMER(id) ON DELETE CASCADE
);CREATE TABLE `ITEMS`(
	`ITEMNO` INT NOT NULL AUTO_INCREMENT,
	`DESCRIPTION` VARCHAR(100) NOT NULL,
	`WEIGHT` DECIMAL(5, 2),
	`COST` DECIMAL(5, 2) NOT NULL,
	PRIMARY KEY(`ITEMNO`)
);CREATE TABLE item_orders (
	`id` serial,
	`item_id` int NOT NULL,
	`order_id` int NOT NULL,
	`order_date` timestamp,
	`return_date` timestamp,
	PRIMARY KEY (id),
	FOREIGN KEY (item_id) REFERENCES ITEMS(ITEMNO) ON DELETE CASCADE,
	FOREIGN KEY (order_id) REFERENCES ORDERS(ONO) ON DELETE CASCADE
);CREATE TABLE store_item (
	`id` serial,
	`item_id` int NOT NULL,
	`store_id` int NOT NULL,
	`quatity` int,
	PRIMARY KEY (id),
	FOREIGN KEY (item_id) REFERENCES ITEMS(ITEMNO) ON DELETE CASCADE,
	FOREIGN KEY (sid) REFERENCES STORES(sid) ON DELETE CASCADE
);